// awlWords.ts
export const AWL: string [] = [
    "sector", "available", "financial", "process", "individual", "specific", "principle", "estimate", "variable", "method", "datum", "research", "contract", "environment", "export", "source", "assessment", "policy", "identify", "create", "derive", "factor", "procedure", "definition", "assume", "theory", "benefit", "evidence", "establish", "authority", "major", "issue", "labor", "occur", "economic", "involve", "percent", "interpretation", "consistent", "income", "structure", "legal", "concept", "formula", "section", "require", "constitutional", "analysis", "distribution", "function", "area", "approach", "role", "legislation", "indicate", "response", "period", "context", "significant", "similar",
    "community", "resident", "range", "construction", "strategy", "element", "previous", "conclusion", "security", "aspect", "acquisition", "feature", "text", "commission", "regulation", "computer", "item", "consumer", "achieve", "final", "positive", "evaluation", "assistance", "normal", "relevant", "distinction", "region", "traditional", "impact", "consequence", "chapter", "equation", "appropriate", "resource", "participation", "survey", "potential", "cultural", "transfer", "select", "credit", "affect", "category", "perceive", "seek", "focus", "purchase", "injury", "site", "journal", "primary", "complex", "institute", "investment", "administration", "maintenance", "design", "obtain", "restrict", "conduct",
    "comment", "convention", "publish", "framework", "imply", "negative", "dominant", "illustrate", "outcome", "constant", "shift", "deduction", "ensure", "specify", "justification", "fund", "reliance", "physical", "partnership", "location", "link", "coordination", "alternative", "initial", "validity", "task", "technique", "exclude", "consent", "proportion", "demonstrate", "reaction", "criterion", "minority", "technology", "philosophy", "remove", "sex", "compensation", "sequence", "correspond", "maximum", "circumstance", "instance", "considerable", "sufficient", "corporate", "interaction", "contribution", "immigration", "component", "constraint", "technical", "emphasis", "scheme", "layer", "volume", "document", "register", "core",
    "overall", "emerge", "regime", "implement", "project", "hence", "occupational", "internal", "goal", "retain", "sum", "integration", "mechanism", "parallel", "impose", "despite", "job", "parameter", "approximate", "label", "concentration", "principal", "series", "predict", "summary", "attitude", "undertake", "cycle", "communication", "ethnic", "hypothesis", "professional", "status", "conference", "attribute", "annual", "obvious", "error", "implication", "apparent", "commitment", "subsequent", "debate", "dimension", "promote", "statistic", "option", "domestic", "output", "access", "code", "investigation", "phase", "prior", "grant", "stress", "civil", "contrast", "resolution", "adequate",
    "alter", "stability", "energy", "aware", "license", "enforcement", "draft", "style", "precise", "medical", "pursue", "symbolic", "marginal", "capacity", "generation", "exposure", "decline", "academic", "modify", "external", "psychology", "fundamental", "adjustment", "ratio", "whereas", "enable", "version", "perspective", "contact", "network", "facilitate", "welfare", "transition", "amendment", "logic", "reject", "expansion", "clause", "prime", "target", "objective", "sustainable", "equivalent", "liberal", "notion", "substitution", "generate", "trend", "revenue", "compound", "evolution", "conflict", "image", "discretion", "entity", "orientation", "consultation", "mental", "monitor", "challenge",
    "intelligence", "transformation", "presumption", "acknowledge", "utility", "furthermore", "accurate", "diversity", "attach", "recovery", "assign", "tape", "motivation", "bond", "edition", "nevertheless", "transport", "cite", "fee", "scope", "enhance", "incorporate", "instruction", "subsidiary", "input", "abstract", "ministry", "capable", "expert", "precede", "display", "incentive", "inhibition", "trace", "ignorant", "incidence", "estate", "cooperative", "reveal", "index", "lecture", "discrimination", "overseas", "explicit", "aggregate", "gender", "underlying", "brief", "domain", "rational", "minimum", "interval", "neutral", "migration", "flexibility", "federal", "author", "initiative", "allocate", "exceed",
    "intervention", "confirm", "definite", "classical", "chemical", "voluntary", "release", "visible", "finite", "publication", "channel", "file", "thesis", "equipment", "disposal", "solely", "deny", "identical", "submit", "grade", "phenomenon", "paradigm", "ultimately", "extract", "survive", "convert", "transmission", "global", "infer", "guarantee", "advocate", "dynamic", "simulation", "topic", "insert", "reverse", "decade", "comprise", "hierarchical", "unique", "comprehensive", "couple", "mode", "differentiate", "eliminate", "priority", "empirical", "ideology", "somewhat", "aid", "foundation", "adult", "adaptation", "quotation", "contrary", "media", "successive", "innovation", "prohibit", "isolate",
    "highlight", "eventually", "inspection", "termination", "displacement", "arbitrary", "reinforce", "denote", "offset", "exploit", "detect", "abandon", "random", "revision", "virtually", "uniform", "predominantly", "thereby", "implicit", "tension", "ambiguous", "vehicle", "clarity", "conformity", "contemporary", "automatically", "accumulate", "appendix", "widespread", "infrastructure", "deviation", "fluctuation", "restore", "guideline", "commodity", "minimize", "practitioner", "radical", "plus", "visual", "chart", "appreciation", "prospect", "dramatic", "contradiction", "currency", "inevitably", "complement", "accompany", "paragraph", "induce", "schedule", "intensity", "crucial", "via", "exhibit", "bias", "manipulate", "theme", "nuclear",
    "bulk", "behalf", "unify", "commence", "erosion", "anticipate", "minimal", "cease", "vision", "mutual", "norm", "intermediate", "manual", "supplementary", "incompatible", "concurrent", "ethical", "preliminary", "integral", "conversely", "relax", "confine", "accommodation", "temporary", "distort", "passive", "subordinate", "analogous", "military", "scenario", "revolution", "diminish", "coherence", "suspend", "mature", "assurance", "rigid", "controversy", "sphere", "mediation", "format", "trigger", "qualitative", "portion", "medium", "coincide", "violation", "device", "insight", "refine", "devote", "team", "overlap", "attain", "restraint", "inherent", "route", "protocol", "found", "duration",
    "whereby", "inclination", "encounter", "convince", "assembly", "albeit", "enormous", "reluctant", "pose", "persistent", "undergo", "notwithstanding", "straightforward", "panel", "odd", "intrinsic", "compile", "adjacent", "integrity", "forthcoming", "conceive", "ongoing", "so-called", "likewise", "nonetheless", "levy", "invoke", "colleague", "depression", "collapse"
  ];
  